# Generated by Django 3.1.6 on 2021-04-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uploadfile',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='books',
            new_name='book',
        ),
    ]
