# Generated by Django 3.1.6 on 2021-04-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210408_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='icon',
            field=models.FileField(blank=True, upload_to='icons/'),
        ),
    ]
